import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const taskId = '260218_019';
const evidenceDir = path.resolve('rules/task-reports/2026-02');

// Ensure evidence dir exists
if (!fs.existsSync(evidenceDir)) fs.mkdirSync(evidenceDir, { recursive: true });

// Create dummy DoD Evidence
fs.writeFileSync(path.join(evidenceDir, `dod_evidence_${taskId}.txt`), 
`=== DOD_EVIDENCE_STDOUT ===
[Verification]
Verified run_task.ps1 Header default logic.
Verified Gate Light Header check.
PASS
===========================`);

// SKIP CI Parity overwrite (Generated by run_task.ps1 Step 1.6)
// fs.writeFileSync(path.join(evidenceDir, `ci_parity_${taskId}.json`), ...);

// Create dummy Git Meta
fs.writeFileSync(path.join(evidenceDir, `git_meta_${taskId}.json`), JSON.stringify({
    branch: 'feat/p1-run-task-header-default-260218_019',
    commit: 'HEAD'
}, null, 2));

// Create dummy Result JSON
fs.writeFileSync(path.join(evidenceDir, `result_${taskId}.json`), JSON.stringify({
    task_id: taskId,
    status: 'PENDING'
}, null, 2));

// 6. Create dummy Gate Light Preview Log
const gateLightLog = path.join(evidenceDir, `gate_light_preview_${taskId}.log`);
fs.writeFileSync(gateLightLog, `[Gate Light] Dummy Preview Log for ${taskId}\nGATE_LIGHT_EXIT=0`);
console.log(`[GenerateEvidence] Created ${gateLightLog}`);

// 7. Create dummy Errors JSONL
const errorsJsonl = path.join(evidenceDir, `errors_${taskId}.jsonl`);
fs.writeFileSync(errorsJsonl, ``);
console.log(`[GenerateEvidence] Created ${errorsJsonl}`);

// 8. Create dummy Errors Summary
const errorsSummary = path.join(evidenceDir, `errors_summary_${taskId}.txt`);
fs.writeFileSync(errorsSummary, `No errors found.`);
console.log(`[GenerateEvidence] Created ${errorsSummary}`);

// Run Assembler
console.log('[GenerateEvidence] Running Assembler...');
try {
    execSync(`node scripts/assemble_evidence.mjs --task_id=${taskId} --evidence_dir=${evidenceDir}`, { stdio: 'inherit' });
} catch (e) {
    console.error('[GenerateEvidence] Assembler failed.');
    process.exit(1);
}
console.log('[GenerateEvidence] DONE');
