
import fs from 'fs';
import path from 'path';

/**
 * Evidence Assembler
 * Centralized tool to assemble notify/snippet files from single sources of truth.
 * Ensures no missing blocks and standardizes output.
 */

const ARGS = process.argv.slice(2);
const taskId = ARGS.find(arg => arg.startsWith('--task_id='))?.split('=')[1];
const evidenceDir = ARGS.find(arg => arg.startsWith('--evidence_dir='))?.split('=')[1] || `rules/task-reports/${new Date().toISOString().slice(0, 7)}`;

if (!taskId) {
    console.error('Usage: node scripts/assemble_evidence.mjs --task_id=<id> [--evidence_dir=<path>]');
    process.exit(1);
}

const resolvePath = (filename) => path.resolve(evidenceDir, filename);

// --- 1. Define Inputs (Single Sources of Truth) ---
const inputs = {
    ciParity: resolvePath(`ci_parity_${taskId}.json`),
    gateLightLog: resolvePath(`gate_light_preview_${taskId}.log`),
    dodEvidence: resolvePath(`dod_evidence_${taskId}.txt`),
    gitMeta: resolvePath(`git_meta_${taskId}.json`),
    attestation: resolvePath(`preflight_attestation_${taskId}.json`)
};

// --- 2. Read & Validate Inputs ---
console.log(`[Assembler] Reading inputs for Task ${taskId} from ${evidenceDir}...`);

const missingInputs = Object.entries(inputs).filter(([key, path]) => !fs.existsSync(path));
if (missingInputs.length > 0) {
    console.error(`[Assembler] FAIL: Missing required input files:`);
    missingInputs.forEach(([key, path]) => console.error(`  - ${key}: ${path}`));
    process.exit(1);
}

// Helper to read text
const readText = (path) => fs.readFileSync(path, 'utf8').trim();
// Helper to read JSON
const readJson = (path) => JSON.parse(fs.readFileSync(path, 'utf8').replace(/^\uFEFF/, ''));

const ciParityData = readJson(inputs.ciParity);
const gateLightLog = readText(inputs.gateLightLog);
const dodEvidence = readText(inputs.dodEvidence);
const gitMeta = readJson(inputs.gitMeta);
const attestation = readJson(inputs.attestation);

// --- 3. Extract Blocks ---

// Block 1: CI Parity Preview
// We reconstruct the block from JSON data to ensure format, OR we could read a pre-generated block file.
// Prompt says: "ci_parity_<task_id>.json -> 生成 === CI_PARITY_PREVIEW ==="
const ciParityBlock = `=== CI_PARITY_PREVIEW ===
Base: ${ciParityData.base || ciParityData.base_commit}
Head: ${ciParityData.head || ciParityData.head_commit}
MergeBase: ${ciParityData.merge_base}
Source: JSON (Evidence-as-Code)
Scope: ${ciParityData.files_count} files
Files (Top 3):
${(ciParityData.files_list || []).slice(0, 3).map(f => `  - ${f}`).join('\n')}
  ... (truncated)
=========================`;

// Block 2: Gate Light Preview
// Extract from log. Must find the section.
const gateLightStartMarker = '=== GATE_LIGHT_PREVIEW ===';
// The log usually contains the marker if we printed it. 
// If the log is just the raw output of gate_light_ci, we need to wrap it.
// But wait, prompt says: "gate_light_ci_<task_id>.txt -> 截取 === GATE_LIGHT_PREVIEW ==="
// AND "Must contain === GATE_LIGHT_PREVIEW === (real log substring)"
// If Pass 1 gate_light just outputted logs, we should probably take the whole relevant part.
// Let's assume the Pass 1 log *is* the preview content, or we wrap it.
// But checking "GATE_LIGHT_EXIT=0" is required.
if (!gateLightLog.includes('GATE_LIGHT_EXIT=0')) {
    console.error('[Assembler] FAIL: Gate Light log does not contain "GATE_LIGHT_EXIT=0". Pass 1 failed?');
    process.exit(1);
}

// We wrap the whole log as the preview if it doesn't already have the header.
let gateLightBlock = gateLightLog;
if (!gateLightBlock.includes('=== GATE_LIGHT_PREVIEW ===')) {
    gateLightBlock = `=== GATE_LIGHT_PREVIEW ===\n${gateLightLog}\n==========================`;
} else {
    // Extract the block if it exists (robustness)
    const match = gateLightLog.match(/=== GATE_LIGHT_PREVIEW ===[\s\S]*?GATE_LIGHT_EXIT=0/);
    if (match) {
        gateLightBlock = match[0];
    }
}

// Block 3: DoD Evidence Stdout
let dodBlock = dodEvidence;
if (!dodBlock.includes('=== DOD_EVIDENCE_STDOUT ===')) {
    dodBlock = `=== DOD_EVIDENCE_STDOUT ===\n${dodEvidence}\n===========================`;
}

// --- 4. Assemble Content ---

const header = `Trae Task Report
Task ID: ${taskId}
Date: ${new Date().toISOString()}
Branch: ${gitMeta.branch}
Commit: ${gitMeta.commit}
Scope Diff: ${gitMeta.scope_diff || 'N/A'}
`;

const snippetContent = `${header}

${dodBlock}

${gateLightBlock}

[Generated by scripts/assemble_evidence.mjs]
`;

const notifyContent = `${header}

Status: MERGE-READY (Gate Light PASS)

${ciParityBlock}

${gateLightBlock}

[Generated by scripts/assemble_evidence.mjs]
`;

// --- 5. Validate Blocks (Self-Correction/Check) ---
const checkBlocks = (content, name) => {
    const missing = [];
    if (!content.includes('=== DOD_EVIDENCE_STDOUT ===') && name === 'snippet') missing.push('DOD_EVIDENCE_STDOUT');
    if (!content.includes('=== CI_PARITY_PREVIEW ===') && name === 'notify') missing.push('CI_PARITY_PREVIEW'); 
    // Wait, prompt says: "notify/snippet 必须同时包含三段" (Both must contain all 3 blocks?)
    // Prompt: "notify_260215_010.txt 与 trae_report_snippet_260215_010.txt 均包含三段块：STDOUT / CI_PARITY_PREVIEW / GATE_LIGHT_PREVIEW"
    // Okay, I must include ALL 3 blocks in BOTH files.
    
    if (!content.includes('=== GATE_LIGHT_PREVIEW ===')) missing.push('GATE_LIGHT_PREVIEW');
    return missing;
};

// Re-assemble to include all 3 blocks in both as requested
const fullContent = `${header}

${dodBlock}

${ciParityBlock}

${gateLightBlock}

[Generated by scripts/assemble_evidence.mjs]
`;

// Prompt implication: 
// notify is for PR comment / quick view. 
// snippet is for "trae_report_snippet".
// Usually notify is shorter. But the prompt explicitly demands "均包含三段块".
// So I will make them identical or very similar in terms of evidence blocks.

const notifyMissing = [
    !fullContent.includes('=== DOD_EVIDENCE_STDOUT ===') ? 'DOD_EVIDENCE_STDOUT' : null,
    !fullContent.includes('=== CI_PARITY_PREVIEW ===') ? 'CI_PARITY_PREVIEW' : null,
    !fullContent.includes('=== GATE_LIGHT_PREVIEW ===') ? 'GATE_LIGHT_PREVIEW' : null,
].filter(Boolean);

if (notifyMissing.length > 0) {
    console.error(`[Assembler] FAIL: Generated content missing blocks: ${notifyMissing.join(', ')}`);
    process.exit(1);
}

// --- 6. Write Outputs ---
const notifyPath = resolvePath(`notify_${taskId}.txt`);
const snippetPath = resolvePath(`trae_report_snippet_${taskId}.txt`);

fs.writeFileSync(notifyPath, fullContent);
fs.writeFileSync(snippetPath, fullContent); // They are identical now based on the requirement

console.log(`[Assembler] SUCCESS: Assembled evidence for Task ${taskId}.`);
console.log(`  - ${notifyPath}`);
console.log(`  - ${snippetPath}`);
