import fs from 'fs';
import path from 'path';

/**
 * Appends per-task error logs to the global error stats index.
 * 
 * Usage:
 * node scripts/error_stats_append.mjs --task_id <id> --run_id <id> --commit <hash> --mode <mode> [--source_errors <path>] [--output_index <path>]
 */

const getArg = (args, key) => {
    const prefix = `--${key}=`;
    const arg = args.find(a => a.startsWith(prefix));
    if (arg) return arg.substring(prefix.length);
    const idx = args.indexOf(`--${key}`);
    if (idx !== -1 && idx < args.length - 1) return args[idx + 1];
    return null;
};

const args = process.argv.slice(2);
const taskId = getArg(args, 'task_id');
const runId = getArg(args, 'run_id');
const commit = getArg(args, 'commit');
const mode = getArg(args, 'mode');
let sourceErrors = getArg(args, 'source_errors');
const outputIndex = getArg(args, 'output_index') || 'rules/task-reports/index/error_stats.jsonl';

if (!taskId || !runId || !commit || !mode) {
    console.error('Usage: node scripts/error_stats_append.mjs --task_id <id> --run_id <id> --commit <hash> --mode <mode> [--source_errors <path>] [--output_index <path>]');
    process.exit(1);
}

// Resolve source path if not provided
if (!sourceErrors) {
    const datePart = taskId.split('_')[0]; // 260218
    if (datePart.length === 6) {
        const year = '20' + datePart.substring(0, 2);
        const month = datePart.substring(2, 4);
        sourceErrors = path.join('rules/task-reports', `${year}-${month}`, `errors_${taskId}.jsonl`);
    } else {
        // Fallback or error? Let's try to assume current month if task_id format is weird, 
        // but for now assume standard format.
        console.error(`Cannot deduce source path from task_id: ${taskId}`);
        process.exit(1);
    }
}

if (!fs.existsSync(sourceErrors)) {
    console.error(`Source errors file not found: ${sourceErrors}`);
    process.exit(1);
}

// Ensure output directory exists
const outputDir = path.dirname(outputIndex);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// Severity Mapping
const SEVERITY_MAP = {
    'FAIL_ROOT_CAUSE_BLOCK': 'P0',
    'OPEN_PR_GUARD_BLOCKED': 'P0',
    'GATE_LIGHT_FAILURE': 'P1',
    'SHELL_EXIT_NONZERO': 'P1',
    'UNKNOWN_ERROR': 'P1',
    'RESOURCE_EXHAUSTED': 'P2',
    'TEST_FAILURE': 'P2',
    'LINT_ERROR': 'P3',
    'NO_ERROR': 'INFO'
};

const getSeverity = (cls) => SEVERITY_MAP[cls] || 'P2';

// Read source errors
const fileContent = fs.readFileSync(sourceErrors, 'utf-8');
const lines = fileContent.split('\n').filter(line => line.trim());
const records = lines.map(line => {
    try {
        return JSON.parse(line);
    } catch (e) {
        return null;
    }
}).filter(r => r);

if (records.length === 0) {
    console.warn('No records found in source file.');
    // Should we force a NO_ERROR? The source file should have had one if generated by digest.
}

const indexRecords = records.map(r => {
    const severity = getSeverity(r.error_class);
    // Construct message from available fields
    let msg = r.message;
    if (!msg) {
        if (r.error_class === 'NO_ERROR') {
            msg = 'No errors found.';
        } else {
            msg = `[${r.step}] ${r.command} (Exit ${r.exit_code})`;
            if (r.stderr_tail) msg += ` | Stderr: ${r.stderr_tail.substring(0, 100)}...`;
            else if (r.stdout_tail) msg += ` | Stdout: ${r.stdout_tail.substring(0, 100)}...`;
        }
    }

    return {
        task_id: taskId,
        run_id: runId,
        commit: commit,
        ts: r.ts || new Date().toISOString(),
        mode: mode,
        error_class: r.error_class || 'UNKNOWN',
        severity: severity,
        message: msg,
        hint: r.hint || ''
    };
});

// Append to index
if (indexRecords.length > 0) {
    const contentToAppend = indexRecords.map(r => JSON.stringify(r)).join('\n') + '\n';
    fs.appendFileSync(outputIndex, contentToAppend, 'utf-8');
    console.log(`Appended ${indexRecords.length} records to ${outputIndex}`);
} else {
    console.log('No records to append.');
}
