import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { buildStandardResult, ensureDir, parseVerifyArgs, writeStandardLog } from './verify_standard_v1.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

const DEFAULT_TASK_ID = '260406_003';
const DEFAULT_BASE_URL = 'http://localhost:53123';
const REAL_TASK_ID = '260405_017';
const REAL_NOTIFY_FILE = 'rules/task-reports/2026-04/notify_260405_012.txt';

const parseArgs = () => parseVerifyArgs({
  defaultTaskId: DEFAULT_TASK_ID,
  defaultBaseUrl: DEFAULT_BASE_URL,
  defaultOutputSuffix: 'truth_audit_governance_real_task_trial_260406_003',
  defaultSampleName: 'governance_real_task_trial'
});

const extractLine = (text, key) => {
  const m = String(text || '').match(new RegExp(`^${key}:\\s*(.+)$`, 'mi'));
  return m ? m[1].trim() : null;
};

const main = async () => {
  const args = parseArgs();
  const taskDocPath = path.join(REPO_ROOT, 'docs', 'tasks', `${REAL_TASK_ID}.md`);
  const auditScriptPath = path.join(REPO_ROOT, 'scripts', `truth_audit_notify_binding_live_head_${REAL_TASK_ID}.mjs`);
  const notifyPath = path.join(REPO_ROOT, REAL_NOTIFY_FILE.replaceAll('/', path.sep));
  const planPath = path.join(REPO_ROOT, 'docs', 'plans', '260406_thin_governance_moderate_test_plan.md');

  const taskDocExists = fs.existsSync(taskDocPath);
  const auditScriptExists = fs.existsSync(auditScriptPath);
  const notifyExists = fs.existsSync(notifyPath);
  const planExists = fs.existsSync(planPath);

  const taskDoc = taskDocExists ? fs.readFileSync(taskDocPath, 'utf8') : '';
  const auditScript = auditScriptExists ? fs.readFileSync(auditScriptPath, 'utf8') : '';
  const notify = notifyExists ? fs.readFileSync(notifyPath, 'utf8') : '';
  const plan = planExists ? fs.readFileSync(planPath, 'utf8') : '';

  const declaredLineage = /lineage ancestor/i.test(taskDoc);
  const declaredStrict = /strict equality/i.test(taskDoc);
  const modeDeclaredByAudit = /generated_from_head_is_ancestor_of_live_head|notify_commit_matches_live_head_commit/i.test(auditScript);
  const modeDeclared = declaredLineage || declaredStrict || modeDeclaredByAudit;

  const artifactTaskId = extractLine(notify, 'Artifact Task ID');
  const regeneratedByTask = extractLine(notify, 'Regenerated By Task');
  const generatedFromHead = extractLine(notify, 'Generated From Head');

  const checks = {
    real_task_doc_exists: taskDocExists,
    real_task_audit_script_exists: auditScriptExists,
    real_notify_exists: notifyExists,
    real_task_declares_mode: modeDeclared,
    real_notify_identity_fields_complete: !!artifactTaskId && !!regeneratedByTask && !!generatedFromHead,
    real_notify_regenerated_by_matches_real_task: regeneratedByTask === REAL_TASK_ID,
    plan_has_task_003_real_trial_clause: /260406_003：绑定下一条真实任务试运行/.test(plan),
    governance_substitute_pass: false
  };
  checks.governance_substitute_pass = Object.entries(checks)
    .filter(([k]) => k !== 'governance_substitute_pass')
    .every(([, v]) => Boolean(v));

  const pass = checks.governance_substitute_pass;
  const firstBreakLayer = pass ? 'NONE_CHAIN_PASS' : 'governance_real_task_trial';
  const standard = buildStandardResult({
    scriptName: 'truth_audit_governance_real_task_trial_260406_003',
    taskId: args.taskId,
    sampleName: args.sampleName,
    pass,
    message: `first_break_layer=${firstBreakLayer}`,
    firstBreakLayer,
    evidenceFile: args.output,
    summary: { pass, first_break_layer: firstBreakLayer, checks },
    rawExcerpt: {
      fail_to_pass: {
        before: 'real_task_trial_not_bound',
        after: pass ? 'real_task_trial_bound' : 'real_task_trial_still_broken'
      },
      governance_substitute: {
        pass: checks.governance_substitute_pass
      },
      checks,
      sample_rows: [
        { is_real_runtime: true, file: `docs/tasks/${REAL_TASK_ID}.md` },
        { is_real_runtime: true, file: REAL_NOTIFY_FILE }
      ]
    }
  });

  ensureDir(args.output);
  fs.writeFileSync(args.output, JSON.stringify({ ...standard, task_id: args.taskId, task_type: 'workflow_upgrade', checks }, null, 2));
  const verifyLog = writeStandardLog(args.output, standard);
  console.log(`VERIFY_OUTPUT=${args.output}`);
  console.log(`VERIFY_LOG=${verifyLog}`);
  console.log(JSON.stringify({ pass, first_break_layer: firstBreakLayer, checks }));
  if (!pass) process.exitCode = 1;
};

main().catch((error) => {
  console.error(error?.message || String(error));
  process.exit(1);
});
