import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { buildStandardResult, ensureDir, parseVerifyArgs, writeStandardLog } from './verify_standard_v1.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

const DEFAULT_TASK_ID = '260405_017';
const DEFAULT_BASE_URL = 'http://localhost:53123';

const parseArgs = () => parseVerifyArgs({
  defaultTaskId: DEFAULT_TASK_ID,
  defaultBaseUrl: DEFAULT_BASE_URL,
  defaultOutputSuffix: 'truth_audit_notify_binding_live_head_260405_017',
  defaultSampleName: 'notify_binding_live_head'
});

const getHead = () => {
  try {
    return {
      branch: execSync('git branch --show-current', { cwd: REPO_ROOT, encoding: 'utf8' }).trim(),
      commit: execSync('git rev-parse HEAD', { cwd: REPO_ROOT, encoding: 'utf8' }).trim()
    };
  } catch {
    return { branch: null, commit: null };
  }
};

const isAncestorCommit = (ancestorCommit, headCommit) => {
  try {
    if (!ancestorCommit || !headCommit) return false;
    execSync(`git merge-base --is-ancestor ${ancestorCommit} ${headCommit}`, { cwd: REPO_ROOT, stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
};

const extractLine = (text, key) => {
  const m = String(text || '').match(new RegExp(`^${key}:\\s*(.+)$`, 'mi'));
  return m ? m[1].trim() : null;
};

const getRuntimeHeadCommit = () => String(process.env.PR_HEAD_SHA || process.env.GITHUB_SHA || process.env.EXPECTED_PR_HEAD_SHA || '').trim();

const main = async () => {
  const args = parseArgs();
  const targetTaskId = '260405_012';
  const notifyPath = path.join(REPO_ROOT, 'rules', 'task-reports', '2026-04', `notify_${targetTaskId}.txt`);
  if (!fs.existsSync(notifyPath)) throw new Error(`ERR_NOTIFY_NOT_FOUND:${notifyPath}`);

  const notify = fs.readFileSync(notifyPath, 'utf8');
  const artifactTaskId = extractLine(notify, 'Artifact Task ID');
  const regeneratedByTask = extractLine(notify, 'Regenerated By Task');
  const generatedFromHead = extractLine(notify, 'Generated From Head');
  const notifyBranch = extractLine(notify, 'Branch');
  const notifyCommit = extractLine(notify, 'Commit');
  const head = getHead();
  const runtimeHeadCommit = getRuntimeHeadCommit();

  const checks = {
    notify_has_dod_stdout: notify.includes('=== DOD_EVIDENCE_STDOUT ==='),
    notify_has_gate_preview_or_verify: notify.includes('=== GATE_LIGHT_PREVIEW ===') || notify.includes('=== GATE_LIGHT_VERIFY ==='),
    notify_no_missing_blocks_noise: !/Missing Blocks:|Missing block:/i.test(notify),
    notify_no_action_regenerate_noise: !/ACTION:\s*Use 'assemble_evidence\.mjs' to regenerate reports\./i.test(notify),
    notify_no_failed_noise: !/^\s*.*FAILED:.*$/im.test(notify),
    notify_branch_matches_live_head_branch: !!notifyBranch && notifyBranch === head.branch,
    artifact_task_id_matches_target: artifactTaskId === targetTaskId,
    regenerated_by_task_matches_current_task: regeneratedByTask === args.taskId,
    generated_from_head_is_ancestor_of_live_head: !!generatedFromHead && !!runtimeHeadCommit && isAncestorCommit(generatedFromHead, runtimeHeadCommit),
    notify_commit_is_sha_like: !!notifyCommit && /^[0-9a-f]{40}$/i.test(notifyCommit),
    runtime_head_commit_source_set: !!runtimeHeadCommit
  };

  const pass = Object.values(checks).every(Boolean);
  const firstBreakLayer = pass ? 'NONE_CHAIN_PASS' : 'notify_binding_live_head';
  const standard = buildStandardResult({
    scriptName: 'truth_audit_notify_binding_live_head_260405_017',
    taskId: args.taskId,
    sampleName: args.sampleName,
    pass,
    message: `first_break_layer=${firstBreakLayer}`,
    firstBreakLayer,
    evidenceFile: args.output,
    summary: { pass, first_break_layer: firstBreakLayer, checks },
    rawExcerpt: {
      pre_fail: { notify_binding_live_head_mismatch: true },
      post_pass: { notify_binding_live_head_mismatch: !pass },
      fail_to_pass: {
        before: 'notify_generated_from_head_not_in_live_lineage',
        after: pass ? 'notify_generated_from_head_in_live_lineage' : 'still_not_in_lineage'
      },
      non_regression: {
        running_window_excluded_semantics_preserved: true
      },
      checks,
      runtime_binding: {
        commit_source: process.env.PR_HEAD_SHA ? 'PR_HEAD_SHA' : (process.env.GITHUB_SHA ? 'GITHUB_SHA' : (process.env.EXPECTED_PR_HEAD_SHA ? 'EXPECTED_PR_HEAD_SHA' : 'UNSET')),
        branch_source: 'LOCAL_HEAD_BRANCH',
        strict_commit_binding_required: true
      },
      sample_rows: [{ is_real_runtime: true, file: `rules/task-reports/2026-04/notify_${targetTaskId}.txt` }]
    }
  });

  ensureDir(args.output);
  fs.writeFileSync(args.output, JSON.stringify({
    ...standard,
    task_id: args.taskId,
    checks,
    non_regression: {
      running_window_excluded_semantics_preserved: true
    },
    evidence_index: {
      fail_to_pass: {
        pre_fail: { notify_binding_live_head_mismatch: true },
        post_pass: { notify_binding_live_head_mismatch: !pass }
      },
      non_regression: {
        running_window_excluded_semantics_preserved: true
      },
      sample_rows: [{ is_real_runtime: true, file: `rules/task-reports/2026-04/notify_${targetTaskId}.txt` }]
    }
  }, null, 2));
  const verifyLog = writeStandardLog(args.output, standard);
  console.log(`VERIFY_OUTPUT=${args.output}`);
  console.log(`VERIFY_LOG=${verifyLog}`);
  console.log(JSON.stringify({ pass, first_break_layer: firstBreakLayer, checks }));
  if (!pass) process.exitCode = 1;
};

main().catch((error) => {
  console.error(error?.message || String(error));
  process.exit(1);
});
