import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { buildStandardResult, ensureDir, parseVerifyArgs, writeStandardLog } from './verify_standard_v1.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');

const DEFAULT_TASK_ID = '260406_002';
const DEFAULT_BASE_URL = 'http://localhost:53123';
const TARGET_NOTIFY_TASK_ID = '260405_012';

const parseArgs = () => parseVerifyArgs({
  defaultTaskId: DEFAULT_TASK_ID,
  defaultBaseUrl: DEFAULT_BASE_URL,
  defaultOutputSuffix: 'truth_audit_governance_t1_t4_260406_002',
  defaultSampleName: 'governance_t1_t4'
});

const extractLine = (text, key) => {
  const m = String(text || '').match(new RegExp(`^${key}:\\s*(.+)$`, 'mi'));
  return m ? m[1].trim() : null;
};

const runtimeHeadCommit = () => String(process.env.PR_HEAD_SHA || process.env.GITHUB_SHA || process.env.EXPECTED_PR_HEAD_SHA || '').trim();

const isAncestorCommit = (ancestorCommit, headCommit) => {
  try {
    if (!ancestorCommit || !headCommit) return false;
    execSync(`git merge-base --is-ancestor ${ancestorCommit} ${headCommit}`, { cwd: REPO_ROOT, stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
};

const getPrDiffFiles = () => {
  try {
    const raw = execSync('git diff --name-only origin/main...HEAD', { cwd: REPO_ROOT, encoding: 'utf8' });
    return raw.split(/\r?\n/).map((x) => x.trim()).filter(Boolean);
  } catch {
    return [];
  }
};

const main = async () => {
  const args = parseArgs();
  const taskDocPath = path.join(REPO_ROOT, 'docs', 'tasks', `${args.taskId}.md`);
  const notifyRelPath = path.join('rules', 'task-reports', '2026-04', `notify_${TARGET_NOTIFY_TASK_ID}.txt`).replace(/\\/g, '/');
  const notifyAbsPath = path.join(REPO_ROOT, notifyRelPath);
  if (!fs.existsSync(taskDocPath)) throw new Error(`ERR_TASK_DOC_NOT_FOUND:${taskDocPath}`);
  if (!fs.existsSync(notifyAbsPath)) throw new Error(`ERR_NOTIFY_NOT_FOUND:${notifyAbsPath}`);

  const taskDoc = fs.readFileSync(taskDocPath, 'utf8');
  const notify = fs.readFileSync(notifyAbsPath, 'utf8');
  const declaredLineage = /口径类型：`lineage ancestor`/.test(taskDoc);
  const declaredStrict = /口径类型：`strict equality`/.test(taskDoc);
  const mode = declaredStrict ? 'strict' : 'ancestor';

  const artifactTaskId = extractLine(notify, 'Artifact Task ID');
  const regeneratedByTask = extractLine(notify, 'Regenerated By Task');
  const generatedFromHead = extractLine(notify, 'Generated From Head');
  const branch = extractLine(notify, 'Branch');
  const commit = extractLine(notify, 'Commit');

  const prFiles = getPrDiffFiles();
  const head = runtimeHeadCommit();
  const relationPass = mode === 'strict'
    ? (!!generatedFromHead && !!head && generatedFromHead === head)
    : (!!generatedFromHead && !!head && isAncestorCommit(generatedFromHead, head));

  const checks = {
    t1_declared_mode_matches_audit_mode: (mode === 'ancestor' && declaredLineage) || (mode === 'strict' && declaredStrict),
    t2_notify_header_fields_complete: !!artifactTaskId && !!regeneratedByTask && !!generatedFromHead && !!branch && !!commit,
    t3_target_notify_readable_in_pr_diff: prFiles.includes(notifyRelPath),
    t4_header_relation_matches_declared_mode: relationPass,
    runtime_head_commit_source_set: !!head,
    governance_substitute_pass: false
  };
  checks.governance_substitute_pass = Object.entries(checks)
    .filter(([k]) => k !== 'governance_substitute_pass')
    .every(([, v]) => Boolean(v));

  const pass = checks.governance_substitute_pass;
  const firstBreakLayer = pass ? 'NONE_CHAIN_PASS' : 'governance_t1_t4';

  const standard = buildStandardResult({
    scriptName: 'truth_audit_governance_t1_t4_260406_002',
    taskId: args.taskId,
    sampleName: args.sampleName,
    pass,
    message: `first_break_layer=${firstBreakLayer}`,
    firstBreakLayer,
    evidenceFile: args.output,
    summary: { pass, first_break_layer: firstBreakLayer, checks },
    rawExcerpt: {
      fail_to_pass: {
        before: 'governance_t1_t4_not_enforced',
        after: pass ? 'governance_t1_t4_enforced' : 'governance_t1_t4_still_broken'
      },
      governance_substitute: {
        pass: checks.governance_substitute_pass
      },
      checks,
      sample_rows: [{ is_real_runtime: true, file: notifyRelPath }]
    }
  });

  ensureDir(args.output);
  fs.writeFileSync(args.output, JSON.stringify({ ...standard, task_id: args.taskId, checks }, null, 2));
  const verifyLog = writeStandardLog(args.output, standard);
  console.log(`VERIFY_OUTPUT=${args.output}`);
  console.log(`VERIFY_LOG=${verifyLog}`);
  console.log(JSON.stringify({ pass, first_break_layer: firstBreakLayer, checks }));
  if (!pass) process.exitCode = 1;
};

main().catch((error) => {
  console.error(error?.message || String(error));
  process.exit(1);
});
